language: objective-c
script:
  - xcrun simctl list
  - instruments -s devices
  - xctool test -project WTValidator.xcodeproj -scheme WTValidator -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO -destination 'platform=iOS Simulator,name=iPhone 6,OS=9.3'
